$TTL 86400
@   IN  SOA ns1.com.ua. admin.com.ua. (
        2024010101 ; Serial
        3600       ; Refresh
        1800       ; Retry
        1209600    ; Expire
        86400 )    ; Minimum TTL
;
@   IN  NS  ns1.com.ua.
@   IN  NS  ns2.com.ua.
ns1.com.ua. IN A 10.0.0.1
ns2.com.ua. IN A 10.0.0.2
google IN A 103.174.6.49
google IN A 179.152.121.80
monobank IN A 6.75.140.191
rozetka IN A 26.190.176.247
